### ISSUE TITLE
Hyphenation Issue

### ISSUE THREAD

**Issue by rehmatworks** [jojoee/medium-clone#9]
Thank you for this great theme. I am having an issue that's related to hyphenation. Words in posts are split (without a hyphen) and it makes it really hard to read. Can you please make it to show the hyphens or can you please disable the hyphenation completely? Adding below CSS rules doesn't work:

```css
p {
-moz-hyphens: none!important;
-ms-hyphens: none!important;
-webkit-hyphens: none!important;
hyphens: none!important;
word-wrap: normal!important;
}
```
And here is a screenshot that highlights a few broken words:
<img width="772" alt="hyphenation" src="https://user-images.githubusercontent.com/23554187/46687572-979f1e80-cc14-11e8-8f68-cee417da90ae.png">
